import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";

import { ThemeProvider } from "./context/ThemeProvider";


export const metadata: Metadata = {
  title: "welderufael's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
          <Header ></Header>

          <div className="h-full pt-8">
            {children}
          </div>

          <Footer></Footer>
        </ThemeProvider>

      </body>
    </html>
  );
}
